### ISSUE TITLE
Is there a way to use this solution without CUDA?

### ISSUE THREAD

**Issue by LeandroFerrazMonteiro** [mazzzystar/randomCNN-voice-transfer#1]
First, thanks for sharing this solution. Pardon me if I'm using the Issues in the wrong way, I am not an expert on programming. I'm trying to run on a laptop without nvdia video card, but pytorch points out that it needs cuda libraries. I know that without CUDA, the process will be more slow.

**Comment by mazzzystar** [comment]
@LeandroFerrazMonteiro 
Hi I think the program can run smoothly even you don't have `CUDA` support. (If error occurs, just remove all the `.cuda()` in code.)

But still, the training time will be 10x - 30x longer for using only 1 cpu on your laptop. So you may be much more patient, and be careful about `RAM` usage.

**Comment by LeandroFerrazMonteiro** [comment]
Doing this fixed the error, thanks. As you said, the training time is very slow, but it's working. Again, thank you. Soon I'll close this issue
