### ISSUE TITLE
How to Train this repo, can you please eloborate ?

### ISSUE THREAD

**Issue by aishweta** [mazzzystar/randomCNN-voice-transfer#4]
Hey @mazzzystar I gone through this repo. It looks good.. I checked audio samples. Would like to do voice cloning / Voice conversion.
How much data we need for training. I didn't seen any data for training. How to evaluate results, where do we found output.
Could you please elaborate this repo.

**Comment by mazzzystar** [comment]
Sorry for late response. 
* Actually this project does NOT need dataset, because we use random parameters CNN. 
* As for evaluation, there is not a good method like Inception Score(IS) or MSE, currently mainly based  mean of score(MOS) .

This project is done a few months ago, I may elaborate it when I'm free.

**Comment by aishweta** [comment]
Thanks for reply. I gone through this your work. and I did. It creating random voice, and currently not able to clone any voice.

**Comment by mazzzystar** [comment]
@shwetagargade216 I'm not sure what do you mean by "random voice", currently it can transfer some voice texture of speaker `A` to speaker `B` while keeping with `B`'s content the result, though the transfer process is not satisfying.
Feel free to reopen this issue.

**Comment by smalissa** [comment]
@mazzzystar 
@shwetagargade216 
hi all
i see this project, it's nice.
itried it on 2 voicce wave to vonvert from one to othe, but how about if i want to do the conversion on a dataset ?
i have a dataset, and want to do the conversion to do it all at once, how?
