### ISSUE TITLE
 Installation Environment

### ISSUE THREAD

**Issue by vangogh0318** [mazzzystar/randomCNN-voice-transfer#5]
hi， I would like to train this demo.  which  is Installation Environment ? python version, pytorch, or other software

thank you.

**Comment by mazzzystar** [comment]
```
python >= 3.6
pytorch >= 0.4
```
All other package environments see in [requirements.txt](https://github.com/mazzzystar/randomCNN-voice-transfer/blob/master/requirements.txt)

**Comment by vangogh0318** [comment]
> ```
> python >= 3.6
> pytorch >= 0.4
> ```
> All other package environments see in [requirements.txt](https://github.com/mazzzystar/randomCNN-voice-transfer/blob/master/requirements.txt)

thanks. I will try
