### ISSUE TITLE
import torch error

### ISSUE THREAD

**Issue by oracle9i88** [mazzzystar/randomCNN-voice-transfer#7]

**Comment by mazzzystar** [comment]
Have you installed [PyTorch](https://pytorch.org/)?

**Comment by oracle9i88** [comment]
oh,mymistake. thank you.

but when I python train.py, then

python: symbol lookup error: /home/oracle9i/anaconda3/envs/random/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack

**Comment by oracle9i88** [comment]
pytorch-gpu?  which cuda vertion?

**Comment by mazzzystar** [comment]
https://pytorch.org/get-started/locally/

You may like to choose the one version fits your GPU and OS. `PyTorch>=0.4` is enough for this project.

**Comment by oracle9i88** [comment]
thanks, how to train my dataset

**Comment by mazzzystar** [comment]
No dataset. Once you install all the dependences, just follow the README

**Comment by oracle9i88** [comment]
The README is too simple.  I wish I can train and create wav file
