### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ghost** [mazzzystar/randomCNN-voice-transfer#8]
Traceback (most recent call last):
  File "train.py", line 75, in <module>
    content_loss = content_param * compute_content_loss(a_C, a_G)
  File "/content/randomCNN-voice-transfer/utils.py", line 64, in compute_content_loss
    J_content = 1.0 / (4 * m * n_C * n_H * n_W) * torch.sum((a_C_unrolled - a_G_unrolled) ** 2)
RuntimeError: CUDA out of memory. Tried to allocate 2.99 GiB (GPU 0; 14.73 GiB total capacity; 10.14 GiB already allocated; 1.89 GiB free; 1.97 GiB cached)

**Comment by mazzzystar** [comment]
Sorry for the late response.
It means your CUDA out of memory. You may try with shorter audio inputs, or change the `N_FFT` to get shorter spectrogram.
